### ISSUE TITLE
random layers

### ISSUE THREAD

**Issue by consier** [tatarize/vpype-dxf#5]
I can't comprehend how `vpype-dxf` reads layers.
It seems that geometry types (`polyline`, `line`, `curve`, etc.) and `color` both interfere with what `vpype-dxf` interprets as layers.

- using a dxf with 3 layers, `vpype-dxf` reads 2 layers. The second and third layer somehow get joined
- using a dxf with 3 layers + 3 colors,  `vpype-dxf` reads 6 layers. They don't seem to make sense at all

**Comment by tatarize** [comment]
Code-wise this should be a pretty reasonable interpolation of `ezdxf`'s code. 

https://ezdxf.readthedocs.io/en/stable/tutorials/layers.html

It reads the geometry objects. And I think it puts each of them in their own layer. 

```python
    from vpype.io import _convert_flattened_paths as i_trample_your_api
    color = None
    for entity in dxf.entities:
        entity_to_svg(elements, dxf, entity, scale)
        if len(elements) > 1:
            new_color = elements[-1].stroke
            if color != new_color:
                lc = i_trample_your_api(elements, quantization, simplify, parallel)
                document.add(lc)
                elements.clear()
                color = new_color
```

It reads the entities and if the the entity has a different color than the previous color it says that that is a new layer and adds that. It should only have as many layers as colors.

**Comment by consier** [comment]
> It should only have as many layers as colors.

I thought so too. I experimented with various dxf files and layer / color / geometry combinations:

when using a dxf with 1 layer that contains only lines in 3 different colors `vpype-dxf` generates 7 layers. Some seemingly random entities of a color-group end up in an additional layer or even in a layer from another color-group. 

I’m not sure if I interpret the code correctly but could this be a draw order issue? Meaning that once an entity with another color comes up, entities with a previous color further down the path cannot be put in the previously generated layer?

**Comment by tatarize** [comment]
I might need some test files, the couple files I had didn't create any more entities than were in the file. Which seems to be the only way I can think to generate more layers than objects. Unless I'm misunderstanding what's wrong here.

**Comment by consier** [comment]
here are some of the files I used: [dxf-files.zip](https://github.com/tatarize/vpype-dxf/files/7644817/dxf-files.zip)

`3colors.dxf` generates 7 layers for me. `3layers.dxf` generates only 2 layers

**Comment by tatarize** [comment]
#0000ff != #ff0000
#ff0000 != #0000ff
#0000ff != #ff0000
#ff0000 != #0000ff
#0000ff != #00ff00
6

Correctly the 3colors should have 6 layers and 3 layers should have 1. There's a bug in the checking routine that makes the first entity always it's own layer.

**Comment by tatarize** [comment]
Okay, fixed the bug so it will still give you weirder layers but it'll be consistent about it. 0.0.5 should be on pypi.

Anytime the color changes that's a new layer even if the color change is to a color that already existed previously. And the dxf layers themselves should be corrected. So 3 layers gives 1 layer and 3 colors which flips between those colors several times ends up with 6 layers.

Now, we can discuss some options to do things a different way. For example map based on color and putting the new entity in the older layer. Likely would need an option or something in `dread` for that.

**Comment by consier** [comment]
> For example map based on color and putting the new entity in the older layer.

in my opinion that would be a very useful improvement.

> Likely would need an option or something in dread for that.

I agree. I think that the code could even be reused to allow for all `entities` to be sorted by `lineweight`, `layer`(original) and maybe also by `group`. 

Using ezdxfs `get_dxf_attrib` [method](https://ezdxf.readthedocs.io/en/stable/dxfentities/dxfentity.html#ezdxf.entities.DXFEntity.get_dxf_attrib) could be useful.

I can read and write python a little bit but that’s it. I’m not sure if I can be of any help.

**Comment by tatarize** [comment]
Yeah, sounds about correct. Unless vpype has some better methods to store the data that I don't know about it'll be lost after initial load. So `group by color` is the current default, and `--map` would be an option. So each color in the document gets its own layer. Declaring map means that those we have 1 color group for each color, and go back and put that data back in the correct color-group regardless of the ordering.

We'd also have `layer` which probably should be the default. Layer on a per entity basis would be fine but that could be done directly in vype. `lineweight` would also be quite reasonable, `linetype`  as well. Since most of these are free I might as well add in `thickness` though it's only an attribute in DXF R2000 and `transparency`. Even though I seriously doubt anybody will use those for much of anything.

**Comment by consier** [comment]
I did some research on `ezdxf`: `all_entities_by_attribute = dxf.query().groupby('color')` seems to do exactly what we are after. `'color'` could be replaced by a variable (linetype, layer, etc.)
I just can't get my head around how color/layer gets managed after `entity_to_svg(elements, dxf, entity, scale)`
anyway, that's what I have so far:

```
    all_entities_by_attribute = dxf.query().groupby('color')
    color = None
    for group in all_entities_by_attribute.values():
        for entity in group:
            entity_to_svg(elements, dxf, entity, scale)
            if len(elements) > 1:
                new_color = elements[-1].stroke
                if color is None:
                    color = new_color
                if color != new_color:
                    lc = i_trample_your_api(elements, quantization, simplify, parallel)
                    document.add(lc)
                    elements.clear()
                    color = new_color
        if len(elements):
            lc = i_trample_your_api(elements, quantization, simplify, parallel)

            document.add(lc)
        return document
```

**Comment by tatarize** [comment]
Hm. It would be far preferred to use as much ezdxf internal code as I can. I'll check up on the query() command there.

**Comment by tatarize** [comment]
That would group them correctly, but I still need to check that property correctly, which makes it *somewhat* moot. Since I still need to get that stuff.

The code there just converts entity_to_svg() since the loading code in vypype is kind of hardcoded as svg. The `i_trample_your_api` is using abey's sort of protected method for loading that data since I'm not re-inventing the wheel. I'm basically converting the data to svg and then call the vpype loading code for that stuff.

**Comment by consier** [comment]
FWIW here ist the link to where I read about it: [link](https://ezdxf.readthedocs.io/en/stable/usage_for_beginners.html#query-dxf-entities)
`query()` can be used to filter for certain geometry

**Comment by tatarize** [comment]
It's a really pretty api, but I'm not sure I can use it effectively given the constraints on the code. Though entity type should certainly be a grouping criteria for the layers. I'm mostly just using ezdxf to get the objects and properties and somewhat pointlessly rewrite them to svg to then feed into vpype.

But, there'd absolutely be something to a more advanced vpype-dxf that relies more heavily on those features. And just feeds the properties you give it into the code. You could call that query() command with a custom filter and groupby() and basically feed that stuff directly into vpype. So if you wanted to load a dxf but only the lines entities you could absolutely filter that really easily by feeding that into query routine there.

In fact I might need to take a step back and see if that's reasonable enough to implement. Since query() is pretty robust it wouldn't be too hard to force feed it a groupby() and query directly from the CLI.

**Comment by tatarize** [comment]
```python

    all_entities_by_attribute = dxf.query(query=query).groupby(groupby)
    for group in all_entities_by_attribute.values():
        for entity in group:
            entity_to_svg(elements, dxf, entity, scale)
            lc = i_trample_your_api(elements, quantization, simplify, parallel)
            document.add(lc)
        elements.clear()
    return document
```

I reconsidered and since we don't really need the fancier stuff and it should run through ezdxf it means if there's not something in there it's up to ezdxf to fix that.

Trying a version in #6

**Comment by tatarize** [comment]
```python
@click.option(
    "-Q",
    "--query",
    type=str,
    default="*",
    help="ezdxf query string. eg. 'LINE', 'LINE[layer==\"MyLayer\"]'",
)
@click.option(
    "-g",
    "--groupby",
    type=str,
    default="color",
    help="Classify layers based on given criteria. color, linewidth, linetype, thickness, transparency",
)
@vp.global_processor
def dread(
    document: vp.Document,
    file,
    quantization: float,
    simplify: bool,
    parallel: bool,
    query: str,
    groupby: str,
) -> vp.Document:
```

The above needs the modified headers to write the query and groupby strings.

**Comment by consier** [comment]
this looks very promising. `groupby` and `query` are a great addition.

~~It does produce a layer for every entity though. Would `entity_to_svg` need adaptation in order for this to work?~~
it works flawlessly

**Comment by tatarize** [comment]
`vpype dread -Q 'LINE CIRCLE[color==1]' 3colors.dxf write lines-only.svg` looks pretty nice.  Takes a bit to get the query fine.

**Comment by consier** [comment]
`vpype dread -g lineweight file.dxf show --colorful
` something like that on a messy file works wonders.
really nice addition! thank you for that 

There is a small typo in the description for --groupby. it should be `lineweight` instead of `linewidth`.

**Comment by tatarize** [comment]
Okay, I'll fix the typo.  It might need some readme changes too. It's just feeding this stuff into ezdxf now (solid suggestion thing, thank you for that and the research behind it). So the readme will need pointing to the ezdxf pages regarding queries.

**Comment by tatarize** [comment]
Played with it a bit. Took a while to figure out what it was doing fully, I just knew it solved the main use-case. That's useful can use `-g center` and get them grouped by circle centers or `radius`. `handle`, `owner` etc. Just any dxf-property which is a lot. Though many things lack them and they don't get put in a group.
